Add custom DOM prop for styles when using AnimatePresence with mode === `popLayout`
motiondivision/motion pull request #2830
Opened 2024-10-11 22:12 UTC by tehbelinda

By default this was using document.head, but that is not always available to where it's rendered, e.g. when using the shadow DOM. Instead, pass the shadow root to the new `parentDOM` prop

Fixes https://github.com/framer/motion/issues/2508

2024-10-24 16:58 UTC, dylank commented
Hey @mattgperry, do you know what the process is to get this change merged?

2024-11-01 16:25 UTC, tehbelinda commented
hi @mattgperry the pipeline is passing and I just updated the latest conflicts on the CHANGELOG, let me know if you are able to review and approve this or is there someone else I should ping? thanks!

2024-11-11 23:01 UTC, dylank commented
@kurtextrem is this something you can help with?

2024-11-12 00:22 UTC, connormdavis commented
@SaeWooKKang @mattgperry this is a blocker for me would be huge to get this merged 🙏

2024-12-02 11:12 UTC, kurtextrem commented
Hey! I had a brief look, it looks good to me. I've forwarded the PR.

2024-12-03 15:13 UTC, mattgperry commented on packages/framer-motion/src/components/AnimatePresence/__tests__/AnimatePresence.test.tsx
> +    test("Can cycle through multiple components with mode === 'popLayout' and dom", async () => {
I'm not 100% on what this test is trying to achieve.

Is it more expected based on the changes that we should check that `style` blocks are being correctly added to the `testDom` elements?

2024-12-03 15:17 UTC, mattgperry requested changes
Thanks for the PR! 

It would be good to duplicate `packages/framer-motion/cypress/integration/animate-presence-pop.ts` and the `animate-presence-pop` and `dev/react/src/tests/animate-presence-pop`, and rerunning all the tests in a situation that uses a new `ShadowRoot`.

Additionally, do we expect other elements to be used other than `ShadowRoot`? It feels to me like `shadowRoot` or `root` might be a more indicative prop name.

2025-01-08 08:38 UTC, tehbelinda commented on packages/framer-motion/src/components/AnimatePresence/__tests__/AnimatePresence.test.tsx
> +    test("Can cycle through multiple components with mode === 'popLayout' and dom", async () => {
I was aiming for that originally but there doesn't seem to be a way to validate the style block is there, so I resorted to having something that at least exercised the prop. But now that I've added the cypress tests per the other comment, that covers it more thoroughly so I'll just remove this. Let me know if you think there should still be something here

2025-01-08 08:41 UTC, tehbelinda commented
Thanks for taking a look @mattgperry ! I've added the tests as requested and updated the prop to `root`

btw as an alternative to enabling the experimental flag to test the shadow dom in cypress, I did try upgrading cypress to 5.2.0 where the behaviour is enabled by default. The tests still passed, but I was wary of mixing the upgrading of a major version in with this in case there was something else I've missed

2025-06-30 13:01 UTC, merged